name             "phpmyadmin"
maintainer       "Eric Bollens"
maintainer_email "eric@eb.io"
license          "BSD"
description      "Install and configure phpMyAdmim"
long_description "Install and configure phpMyAdmin"
version          "1.0.0"
recipe           "default", "Install phpMyAdmin"
recipe           "apache", "Configure phpMyAdmin for Apache"